### PR TITLE
volumes2movie: replaced depreciated movie2avi with writeVideo

### PR DESCRIPTION
**Pull request by jones-michael-s**
Here's a small change to a file in extrafunctions, mostly to try out as my first pull-request but also because the code was using a depreciated Matlab function and was crashing on us.

### CODE REVIEW

**Comment by tiborauer** [comment]
@jones-michael-s, Would not the code crash on earlier MATLABs? Which is the earliest version of MATLAB, which has videoWriter?

**Comment by jones-michael-s** [comment]
Hi Tibor (that was quick!). Mathworks says writeVideo was introduced in R2010b -- I don't know if you're supporting aa before that version. I could change the code to wrap movie2avi in a try-catch and push a new version?

**Comment by tiborauer** [comment]
I do not think we should go back that far! THank you for checking it.
I am merging.

**Comment by tiborauer** [comment]
Could you also observe my PR, too?

**Comment by jones-michael-s** [comment]
I read the pull request and don't have any comments at the moment -- is there any further action I should take?

**Comment by tiborauer** [comment]
You could merge it, then.

Vale,
Tibor

Auer, Tibor M.D. Ph.D.
Research Fellow in MRI
Department of Psychology
Royal Holloway University of London
Egham Hill
Egham
TW20 0EX
United Kingdom
[cid:image001.jpg@01D04F5F.0CADAB60] +44-1784-27-6594
[cid:image002.jpg@01D04F5F.0CADAB60] Tibor.Auer@rhul.ac.uk<mailto:Tibor.Auer@rhul.ac.uk>

[royalhollowaylogo]<https://www.royalholloway.ac.uk/psychology/home.aspx>

**Pull request merged**
