### PR TITLE
Tibor

### PR DESCRIPTION
**Pull request by tiborauer**
- standalone
- report
- qsub (+non DCS)
- diffusion
- MPM fieldmap
- RSA - CoSMoMVPA

### CODE REVIEW

**Comment by jooh** [comment]
Are you ready for me to test this?

**Comment by tiborauer** [comment]
Yes!

Vale,

Auer, Tibor ('99 Ph)

**Comment by jooh** [comment]
You broke the test by cleaning up /imaging/ta02/Temp... Probably I need to make my tests a bit less dependent on hard-coded paths. :-)

Which ds114 version is the BIDS114 user script using? The full version? I downloaded the reduced nipype2017 version, but that one is missing the task you're using...

**Comment by jooh** [comment]
Is this a modified version of ds114? I was hoping these BIDS examples could become the core of a new set of AA tests that are truly site independent, ie do not require access to the CBU imaging system to run.

Similarly, is the 7T BIDS example an original dataset from openneuro?

**Comment by tiborauer** [comment]
And yes, I agree! We have already suggested that these (or the spm demo from Rik) BIDS datasets should be used for benchmarking.

**Comment by jooh** [comment]
Cool. I have a PR coming up that makes it possible to import only a subset of subjects from a BIDS dataset, so I think we'll be able to make this completely programmatic and reproducible.

**Comment by jooh** [comment]
Looks good, all tests passed. Merging...

**Pull request merged**
