### PR TITLE
Major revisions to aaq_qsub (already merged with main branch)

### PR DESCRIPTION
**Pull request by dprice80**
I have merged with rhodri's main as requested in previous pull request

### CODE REVIEW

**Comment by jooh** [comment]
Hi Darren, we are still getting a lot of file permission changes in the diffs. Good to see no more conflicts with base though.

**Comment by dprice80** [comment]
Okay I see why this has happened. I changed all files to 644 folders to 755
as suggested on the link you sent. Those files showing up as having a
permissions change were 755 which was incorrect anyway right? Should we not
set all files to 644. I don't really know what the logic is there but
that's what seems to be suggested.

**Comment by jooh** [comment]
Actually, should we perhaps set permissions consistently to 644 across the board? This PR would do that? Thoughts from @tiborauer @rhodricusack ? Doesn't matter for individual users as long as you set core.filemode=false, but it's a bit untidy that this is apparently inconsistent across files in the repo.

**Comment by tiborauer** [comment]
I am a fan of any consitency! :) Do I need to change anything in my repo for that?

**Comment by jooh** [comment]
No, shouldn't matter. You will notice that a huge number of files will have changed, but the change will be inconsequential. And going forward everything will look nice and tidy for new users.

Anyway, if we're broadly ok with that I might just check out this PR and run the tests.

**Comment by rhodricusack** [comment]
Darren
From your description this all sounds great, it is good to see this code
moving forwards. I look forward to using it in due course.

And thanks all for tidying.
Rhodri

**Comment by dprice80** [comment]
Hopefully when you pull this changes git will update your local file
permissions. I've not tested that but I could quite easily.

**Comment by dprice80** [comment]
If you have git set to ignore permissions then nothing will change, and
your permissions won't affect the main repository.

**Comment by jooh** [comment]
Looks good. Darren, can you pull the current AA master and push, and I will start the tests again (just merged a bunch of new stuff from Tibor)?

No need to make a new pull request btw - this one should update automatically.

**Comment by dprice80** [comment]
Okay will try to do that today.

**Comment by tiborauer** [comment]
@dprice80, I think you should not mix other improvement (e.g. changes to roi xml - remove specific stream names (aamod*00001)) with this PR.

**Comment by tiborauer** [comment]
@dprice80, are you sure it is safe to remove done flag check?

**Comment by dprice80** [comment]
Yes, this was just an additional check I inserted into aaq_qsub.m, To give
you the background: something changed with our Torque server, and errors
were not being reported correctly in the pool object (Russell doesn't know
why). To protect against this event, first I inserted an additional check
when the job goes to finished state to check whether an error message
exists in the Tasks object (which is still there). However, there were a
couple of occasions when the job quit without an error message, but was
reported as finished in the pool object. The job had not actually completed
so the next dependent module would never run. Therefore, I put an
additional check in aaq_qsub.job_monitor() to check that the done flag
exists. However, our file system does not update quickly enough for this to
work reliably (no idea why that is - perhaps this would work fine on other
systems). I still don't know what the root cause of the problem was, but it
is very rare, so I will wait and see if it happens again.

**Comment by jooh** [comment]
Ok, so any further issues to discuss before I start running the tests? @tiborauer ?

**Comment by tiborauer** [comment]
Nothing on my side.

**Comment by dprice80** [comment]
I'm ready. I've committed the latest changes so nothing to add.

**Comment by tiborauer** [comment]
@dprice80, Again, I think you should not mix other improvements with this PR.

**Comment by dprice80** [comment]
Okay, I have undone that last change, and created a new branch.

Darren

**Comment by tiborauer** [comment]
I am close to finish the test and will have a few commits to add. I will submit a PR to you, @dprice80. If you agree with them and accept them, this PR will be automatically updated, so that I can merge.

**Comment by tiborauer** [comment]
@dprice80, I have finished with the tests and submitted a PR to yours (see your v5-devel branch)!

@dprice80 and @jooh, I have updated the testbed (see /imaging/ta02/aa/aatest) to be consitent with recent changes and to rely on 'standard' tasklist where provided.

**Pull request merged**
