### PR TITLE
Tibor

### PR DESCRIPTION
**Pull request by tiborauer**
- qsub without MDCS or PCT
- update MPM to hMRI
- TR in 4D NIfTI header
- bugfixes (issue #142)

### CODE REVIEW

**Comment by jooh** [comment]
Running tests now...

**Comment by jooh** [comment]
I'm getting a crash in aa_modules/aamod_convert_specialseries.m while running through the ASL pipeline. The line below is problematic, because d is a cell array with one entry, not an integer or boolean (ie, can't be used to index into dcmhdr).

spm_file_merge(char(img4D),fname4D,0,dcmhdr{d}.volumeTR);

**Comment by jooh** [comment]
We got past that problem, but MEG_aa fails now - it looks like the cluster job for aamod_importfilesasstream fails to get added. Have you seen this error before?  This is on R2017a.

script: /imaging/jc01/aatest/cbu/MEG_aa.m

```>> MEG_aa  

Please wait a moment, adding <a href = "matlab: cd /home/jc01/matlab/aa5"></a> to the path
Welcome to aa version 5.4.0 (0113f6fc406effc75764c8045f53a8277b9f67bf) May 2018
 If you publish work that has used aa, please cite our manuscript:
 <a href = "http://dx.doi.org/10.3389/fninf.2014.00090">Cusack R, Vicente-Grabovetsky A, Mitchell DJ, Wild CJ, Auer T, L
inke AC, Peelle JE (2015)</a> 
 <a href = "http://dx.doi.org/10.3389/fninf.2014.00090">Automatic analysis (aa): Efficient neuroimaging workflows and parallel processing using Matlab and XML</a>
 <a href = "http://dx.doi.org/10.3389/fninf.2014.00090">Frontiers in Neuroinformatics 8:90</a>

Please visit <a href = "http://automaticanalysis.org">The aa website</a> for more information!
 
Here you can find example <a href = "matlab: cd /home/jc01/matlab/aa5/aa_recipes_and_parametersets">tasklists</a> and <a href = "matlab: cd /home/jc01/matlab/aa5/examples">scripts</a>.
Ready.
Loading of toolbox /imaging/local/software/spm_cbu_svn/releases/spm12_fil_r6906/toolbox/DAiSS/tbx_cfg_bf.m failed.
INFO: aaworker folder aaworker20180502T220702_tp1c0de680 is older than 7 days...Deleting
INFO: aaworker folder aaworker20180502T220937_tp143d373f is older than 7 days...Deleting
INFO: aaworker folder aaworker20180502T222004_tp7e806bb3 is older than 7 days...Deleting
INFO: aaworker folder aaworker20180502T222432_tp98704409 is older than 7 days...Deleting
INFO: aaworker folder aaworker20180502T222432_tp98704409_bck is older than 7 days...Deleting
INFO: utc_time is not found. java function will be used

Loading of toolbox /imaging/local/software/spm_cbu_svn/releases/spm12_fil_r6906/toolbox/DAiSS/tbx_cfg_bf.m failed. 
LI toolbox not found, if you need this you should add it to the matlab path manually, or set aap.directory_conventions.LIdir
AUTOMATIC ANALYSIS 10-May-2018 09:49:31
=============================================================
Parallel process ID 814724 
INFO: Current MATLAB version 9.2.0.556344 (R2017a) suitable for this aa 5.4.0 (0113f6fc406effc75764c8045f53a8277b9f67bf) May 2018

INFO: Current aa version 5.4.0 (0113f6fc406effc75764c8045f53a8277b9f67bf) May 2018 suitable for this user script

INITIALISATION MODULE aamod_checkparameters: Check user parameters
INITIALISATION MODULE aamod_evaluatesubjectnames: Check raw data for subject "S1" - MEG:12  442
INITIALISATION MODULE aamod_evaluatesubjectnames: Check raw data for subject "S2" - MEG:13  133
INITIALISATION MODULE aamod_study_init: aa initialise study
INITIALISATION MODULE aamod_newsubj_init: Create subject directory for subject "S1" - MEG:meg12_0442/120910
INITIALISATION MODULE aamod_newsubj_init: Create subject directory for subject "S2" - MEG:meg13_0133/130315
Stage aamod_meg_maxfilt input meg comes from aamod_meg_get_fif which is 1 dependencies prior
Stage aamod_meg_convert input channellabels comes from aamod_importfilesasstream which is 3 dependencies prior
Stage aamod_meg_convert input meg comes from aamod_meg_maxfilt which is 1 dependencies prior
Stage aamod_meg_denoise_ICA_1 input meg comes from aamod_meg_convert which is 1 dependencies prior
Stage aamod_meg_denoise_ICA_2_applytrajectory input meg comes from aamod_meg_convert which is 2 dependencies prior 
Stage aamod_meg_denoise_ICA_2_applytrajectory input topography comes from aamod_importfilesasstream which is 6 dependencies prior 
Stage aamod_meg_denoise_ICA_2_applytrajectory input meg_ica comes from aamod_meg_denoise_ICA_1 which is 1 dependencies prior
Stage aamod_meg_epochs input meg comes from aamod_meg_denoise_ICA_2_applytrajectory which is 1 dependencies prior
Stage aamod_meg_average input meg comes from aamod_meg_epochs which is 1 dependencies prior
/usr/bin/dot
INFO: pool profile CBU_Cluster found
INFO: pool Torque is detected 
MODULE aamod_importfilesasstream PENDING: Import files as stream for /imaging/jc01/aatest/cbu/tmp/MEG_aa/MEG/aamod_importfilesasstream_00002/done_aamod_importfilesasstream_00002

Jobs in aa queue: 1

Warning: The system time zone setting, 'GB-Eire', does not specify a single time zone unambiguously. It will be treated
as 'Europe/London'. See the <a href="matlab:doc('datetime.TimeZone')">datetime.TimeZone property</a> for details about
specifying time zones. 
> In verifyTimeZone (line 23)
  In datetime (line 515)
  In parallel.internal.cluster.DefaultProperties.getNewJobPropStruct (line 16)
  In parallel.internal.cluster.CJSSupport/buildJob (line 158)
  In parallel.cluster.CJSCluster/buildIndependentJob (line 462)
  In parallel.Cluster/createJob (line 50)
  In aaq_qsub/qsub_q_job (line 432)
  In aaq_qsub/add_from_jobqueue (line 478)
  In aaq_qsub/runall (line 172)
  In aa_doprocessing (line 386)
  In MEG_aa (line 45) 
Could not add job. Retrying...
Could not add job. Retrying...
Could not add job. Retrying...
Could not add job. Retrying...
Could not add job. Retrying...
Could not add job. Retrying...
Could not add job. Retrying...
Error using aaq_qsub/add_from_jobqueue (line 530)
The operation "submit" can only be performed on jobs in state "pending".
Error in aaq_qsub/runall (line 172)
                                    obj.add_from_jobqueue(i);
Error in aa_doprocessing (line 386)
        taskqueue.runall(dontcloseexistingworkers, false);```

**Comment by tiborauer** [comment]
I have updated the PR to debug/update qsub; however, it will not solve your issue completely.

It seems that you have an issue with the ‘vanilla’ MATLAB-scheduler integration. This is the error message I get upon submission:

 

Error starting job: Error executing the PBS script command 'qsub'. The reason given is 

 usage: qsub [-a date_time] [-A account_string] [-b secs]

[-c { c[=<INTERVAL>] | s | n }] [-C directive_prefix] [-d path] [-D path]

[-e path] [-h] [-I] [-j oe] [-k {oe}] [-l resource_list] [-m n|{abe}]

[-M user_list] [-N jobname] [-o path] [-p priority] [-q queue] [-r y|n]

[-S path] [-t number_to_submit] [-u user_list] [-X] [-W otherattributes=value...]

[-v variable_list] [-V ] [-z] [script]

 

Most importantly, job submission works if you use qsub_nonDCS (my version of MATLAB-scheduler integration).

 

Vale,

Tibor

 

Auer, Tibor (Ph '99)

**Comment by jooh** [comment]
Ok. So are you saying that the problem is with matlab cluster configuration rather than with AA? Happy to try an older Matlab version if you think that will get the tests running again...

**Comment by tiborauer** [comment]
I figured it out. Sorry! It should wotk now. It was a typo in the submission arguments when MEG is processed

**Comment by jooh** [comment]
That helps, thanks! But now we crash on a missing input stream in MTI (script here: /imaging/jc01/aatest/cbu/MTI_aa.m):

```MODULE aamod_dartel_norm_write RUNNING: SPM dartel write normalised structural to MNI space for /imaging/jc01/aatest/cbu/tmp/MTI_aa/MTI/aamod_dartel_norm_write_00001/S01


**** automatic analysis failed - see reason and line numbers below
No inputs obtained for stream structural 
for help, see the <a href="https://github.com/rhodricusack/automaticanalysis/wiki">aa wiki</a>
Error using aas_log (line 63)
aa error:
No inputs obtained for stream structural```

**Comment by tiborauer** [comment]
Yes! It is something which will affect all DARTEL pipelines. On our last meeting we agreed on keeping stream names consitent and not varying after steps. [This commit](https://github.com/rhodricusack/automaticanalysis/pull/149/commits/e97a882f40dc88190b4a38fb3056c1f6a661af28) modifies structural output of aamod_segment8_multichan to name as such rather than normalised_structural. However, aamod_segment8_multichan does not produce structural in a DARTEL pipeline, because we normalise structural in aamod_dartel_norm_write.
The short solution is to use fully specified streamname. E.g.: aap = aas_renamestream(aap,'aamod_dartel_norm_write_00001','structural','aamod_coreg_extended_1_00001.structural');

The long-term (and more clever) solution will be to allow dynamic removal of an outputstream if not created.

**Comment by jooh** [comment]
Ok, in that case can you update the affected example scripts in the repo? In this case it would be examples/aa_user_MTI.m

**Comment by tiborauer** [comment]
I have updated the PR. I implemented the more clever solution, so you do not need to modify the pipeline.
Please, (re)test!

**Comment by jooh** [comment]
Now I crash on running the very first test, with 

err = 
  MException with properties:

    identifier: 'MATLAB:nonExistentField'
       message: 'Reference to non-existent field 'aap_initial'.'
         cause: {}
         stack: [6×1 struct]

err.stack(1)      
ans = 
  struct with fields:

    file: '/home/jc01/matlab/aa5/aa_engine/aa_doprocessing.m'
    name: 'update_aap'
    line: 403

**Comment by tiborauer** [comment]
Sorry! My mistake! I have updated the PR!

**Comment by jooh** [comment]
Hi Tibor,

Still can't get aa_user_MTI to run I'm afraid:

```**** automatic analysis failed - see reason and line numbers below
Job40 on <a href="matlab: cd('/imaging/jc01/aatest/cbu/tmp/MTI_aa/MTI/aamod_dartel_norm_write_00001/S01')">subject "S01" - MRI:CBU140905_CAMCAN_CALIBRATIONS/20141001_153018</a> had an error: aa error:
No inputs obtained for stream structural! 
        Module aamod_segment8_multichan might not have crteated it.
```

**Comment by tiborauer** [comment]
I have updated the PR!

**Comment by jooh** [comment]
Ok, running the tests again. This could be the one that passes!

**Comment by jooh** [comment]
We still crash on AA MTI. Can you make sure aa_user_MTI runs before updating the PR?

```AUTOMATIC ANALYSIS 12-Jun-2018 14:51:23
=============================================================
Parallel process ID 97540
INFO: Current MATLAB version 9.2.0.556344 (R2017a) suitable for this aa 5.4.0 (cb0cf0b6ff55a35af77465208ac959cc85d43285) Jun 2018 

INFO: Current aa version 5.4.0 (cb0cf0b6ff55a35af77465208ac959cc85d43285) Jun 2018 suitable for this user script

INITIALISATION MODULE aamod_checkparameters: Check user parameters
INITIALISATION MODULE aamod_evaluatesubjectnames: Check raw data for subject "S01" - MRI:140905 
INITIALISATION MODULE aamod_evaluatesubjectnames: Check raw data for subject "S02" - MRI:140910
INITIALISATION MODULE aamod_study_init: aa initialise study
INITIALISATION MODULE aamod_newsubj_init: Create subject directory for subject "S01" - MRI:CBU140905_CAMCAN_CALIBRATIONS/20141001_153018
INITIALISATION MODULE aamod_newsubj_init: Create subject directory for subject "S02" - MRI:CBU140910_CAMCAN_CALIBRATIONS/20141002_155503
Stage aamod_get_dicom_structural input autoidentifyseries comes from aamod_autoidentifyseries_timtrio which is 1 dependencies prior
Stage aamod_convert_structural input dicom_structural comes from aamod_get_dicom_structural which is 1 dependencies prior
Stage aamod_biascorrect_structural input structural comes from aamod_convert_structural which is 1 dependencies prior 
Stage aamod_coreg_extended_1 input structural comes from aamod_biascorrect_structural which is 1 dependencies prior
Stage aamod_segment8_multichan input structural comes from aamod_coreg_extended_1 which is 1 dependencies prior 
Stage aamod_dartel_createtemplate input dartelimported_grey comes from aamod_segment8_multichan which is 1 dependencies prior 
Stage aamod_dartel_createtemplate input dartelimported_white comes from aamod_segment8_multichan which is 1 dependencies prior
Stage aamod_dartel_norm_write input structural comes from aamod_segment8_multichan which is 2 dependencies prior
Stage aamod_dartel_norm_write input dartel_template comes from aamod_dartel_createtemplate which is 1 dependencies prior
Stage aamod_dartel_norm_write input dartel_flowfield comes from aamod_dartel_createtemplate which is 1 dependencies prior
Stage aamod_dartel_norm_write input dartel_templatetomni_xfm comes from aamod_dartel_createtemplate which is 1 dependencies prior
Stage aamod_get_dicom_specialseries input autoidentifyseries comes from aamod_autoidentifyseries_timtrio which is 8 dependencies prior
Stage aamod_convert_specialseries input dicom_MTI comes from aamod_get_dicom_specialseries which is 1 dependencies prior
Stage aamod_MTI2MTR input MTI comes from aamod_convert_specialseries which is 1 dependencies prior
Stage aamod_MTI2MTR input MTI_dicom_header comes from aamod_convert_specialseries which is 1 dependencies prior
Stage aamod_MTI_coreg_extended_2 input t1totemplate_xfm comes from aamod_coreg_extended_1 which is 7 dependencies prior
Stage aamod_MTI_coreg_extended_2 input MTR comes from aamod_MTI2MTR which is 1 dependencies prior
Stage aamod_MTI_coreg_extended_2 input MTI_baseline comes from aamod_MTI2MTR which is 1 dependencies prior
Stage aamod_MTI_coreg_extended_2 input aamod_coreg_extended_1_00001.structural comes from aamod_coreg_extended_1 which is 7 dependencies prior
Stage aamod_MTI_norm_write_dartel input dartel_template comes from aamod_dartel_createtemplate which is 6 dependencies prior
Stage aamod_MTI_norm_write_dartel input dartel_templatetomni_xfm comes from aamod_dartel_norm_write which is 5 dependencies prior
Stage aamod_MTI_norm_write_dartel input dartel_flowfield comes from aamod_dartel_createtemplate which is 6 dependencies prior
Stage aamod_MTI_norm_write_dartel input structural comes from aamod_dartel_norm_write which is 5 dependencies prior
Stage aamod_MTI_norm_write_dartel input MTR comes from aamod_MTI_coreg_extended_2 which is 1 dependencies prior
Stage aamod_MTI_roi_extract input MTR comes from aamod_MTI_norm_write_dartel which is 1 dependencies prior
Stage aamod_MTI_roi_valid input roidata_MTR comes from aamod_MTI_roi_extract which is 1 dependencies prior
Stage aamod_MTI_roi_extract input MTR comes from aamod_MTI_norm_write_dartel which is 1 dependencies prior
Stage aamod_MTI_roi_valid input roidata_MTR comes from aamod_MTI_roi_extract which is 1 dependencies prior
/usr/bin/dot
INFO: pool profile CBU_Cluster found
INFO: pool Torque is detected
WARNING: Renaming output structural of aamod_segment8_multichan_00001 to .
  It might breake dependency for the consecuting module(s).
  Make sure that you know what you are doing!
REMOVED: aamod_segment8_multichan_00001 output stream: structural
WARNING: Renaming output t2 of aamod_segment8_multichan_00001 to .
  It might breake dependency for the consecuting module(s).
  Make sure that you know what you are doing!
REMOVED: aamod_segment8_multichan_00001 output stream: t2
WARNING: Renaming output structural of aamod_segment8_multichan_00001 to .
  It might breake dependency for the consecuting module(s).
  Make sure that you know what you are doing!


**** automatic analysis failed - see reason and line numbers below
ERROR: Stream structural of module aamod_segment8_multichan not found!

**Comment by jooh** [comment]
We made it past MTI, yay! But now we have a crash in aa report during aa_user_diffusion_with_topup:

```K>> err.message
ans =
    'aa error:
     Inputstream dicom_diffusion of module aamod_convert_diffusion_phaseencode_direction_00001 generated by aamod_get_dicom_diffusion_00001 not found!
     '
K>> err.stack(1)
ans = 
  struct with fields:

    file: '/home/jc01/matlab/aa5/aa_engine/aas_log.m'
    name: 'aas_log'
    line: 63
K>> err.stack(2)
ans = 
  struct with fields:

    file: '/home/jc01/matlab/aa5/aa_toolbox/provenance/aa_provenance.m'
    name: 'aa_provenance.addModule'
    line: 243
K>> err.stack(3)
ans = 
  struct with fields:

    file: '/home/jc01/matlab/aa5/aa_toolbox/aa_report.m'
    name: 'aa_report'
    line: 94
K>> err.stack(4)
ans = 
  struct with fields:

    file: '/imaging/jc01/aatest/cbu/aa_user_diffusion_with_topup.m'
    name: 'aa_user_diffusion_with_topup'
    line: 60

**Comment by tiborauer** [comment]
The reporting was not prepared for subsessions (i.e. AP-PA). I have updated the PR.

**Comment by jooh** [comment]
Ok, running the tests again...

**Pull request merged**
