### PR TITLE
Major revisions to aaq_qsub + others

### PR DESCRIPTION
**Pull request by dprice80**
I have added an additional queuing system to aaq_qsub.m, and added lots of features to improve robustness of that function (like error handling, retry blocks etc). This was necessary for the CamCAN pipelines where a typical pipeline contains >100,000 jobs. Most of the code in the main loop has been rewritten for speed and efficiency. For example, rather than getting information from the obj.pool object (which was extremely slow), it is saved to a temporary variable obj.jobinfo, which can then be easily referenced anywhere in the script using the qsub ID.

I have also created a new function aaq_qsub_debug.m that can be run after encountering an error in a remote worker (the use of this function is prompted in the command window). The script opens up the taskqueue, finds the error and runs the same commands locally with dbstop if error command activated. This allows faster debugging.

I have added an option to the MEG maxfilter module to allow movecomp to be switched off.

aas_shell.m I have changed the behaviour to crash by default if the unix command fails (as agreed with Tibor and Johan).

I have kept some of the commented out code in aaq_qsub (not my code). Perhaps that should be deleted?

other minor changes

### CODE REVIEW

**Comment by jooh** [comment]
Hi Darren,

I am finding a little hard to review the changes because you appear to have pushed a bunch of file permissions changes. It's better to set git to ignore these and push again. See this stackoverflow thread: https://stackoverflow.com/questions/28268842/changing-file-mode-permissions-from-100755-to-100644-on-github

Also, it looks like you have merge conflicts with v5-devel. Can you merge v5-devel, resolve whatever conflicts arise and push again?

**Comment by dprice80** [comment]
Okay will do. Thanks

**Comment by tiborauer** [comment]
Because it is a relatively large PR with tons of commits, I suggest you to go through the changes. I am a little bit concerned about aas_addsubject. I remember we have discussed that the change in this PR is likely to break some use cases including MRI pipelines with NIFTI source specified with full filename.

**Comment by dprice80** [comment]
Sorry I forgot to remove those changes in aas_addsubject. That was a
temporary fix for a problem with adding MEG data. It's probably best to
revert back to the original file in that case. I will do this now.

**Pull request closed without merging**
