### PR TITLE
waitforalljobs assignment was missing

### PR DESCRIPTION
**Pull request by dprice80**

### CODE REVIEW

**Comment by tiborauer** [comment]
Why is it important? When does the original solution cause an issue?

**Comment by tiborauer** [comment]
The empty array is a default assignment for class properties.

**Comment by dprice80** [comment]
Strange. It gave me an error, which went away after fix. Will send an
example soon

On 5 Oct 2017 17:09, "Tibor Auer" <notifications@github.com> wrote:

Why is it important? When does the original solution cause an issue?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rhodricusack/automaticanalysis/pull/134#issuecomment-334513730>,
or mute the thread

**Comment by dprice80** [comment]
Okay, I can't replicate the error so I'm not sure why this happened, unfortunately. I think since the default for a hidden variable is false we should just close this PR.

**Pull request closed without merging**
