### PR TITLE
Refactor example scripts for portability, implement basic automated testing

### PR DESCRIPTION
**Pull request by jooh**
This is a big one! This pull request tries to achieve two major objectives, which I will cover first. Then I'll mention a few minor changes that have also crept into this PR.

I highly recommend that you check out this pull request locally and try running the tests. I have reorganised the repo a bit so it might also be more apparent how things look now by just checking it out for yourself.

# Major changes

1. Easier to get started with aa - the examples are shorter, have documentation, and should *just run* (famous last words) on a new machine, thanks to many under the hood changes to how AA defines file paths.

2. Rudimentary automated testing that runs through the examples above.

To achieve this I added many under-the-hood features:

* shell expansion in aarecipe - you can reference any shell $variable or $(expression) in any XML field, and the result will be evaluated at run-time.

* aarecipe looks for aap_parameters_user.xml if no defaults.xml file is specified. If this file does not exist, aarecipe can generate it by asking the user to select one of the existing defaults as the parent.

* default aap.acq_details.root - use the above functionality to place data in sensible default locations ($HOME/aa in defaults.xml, /imaging/$USER/aa in defaults_CBSU.xml).

* We now setenv an SPMDIR shell variable to make it easy to reference SPM-relative paths in defaults and tasklists, using the above expansion functionality.

* BIDS import improvements: select custom events.tsv column for first-level model regressor definition, select sub-set of subjects.

* handy function for automatically downloading the aa demo dataset from Rhodri's S3 storage, if it's needed.

# Minor changes

* all roi_extract modules now expect input from the rois stream instead of the ROIFile option. This makes AA more modular and flexible. You will need to modify user scripts by adding aas_addinitialstream.

* quieter, less repetitive logging, especially when using aas_shell

* new modules to reorient nifti header dimensions to the format expected by fslview and similarly stupid viewers.

* Update CBSU default with new version of various toolboxes. Lock versions to specific versions rather than referencing 'latest' for greater reproducibility. Set more sensible defaults (e.g., numdummies should arguably default to 0).

* removed old code: aa_config, aas_configforSPM12, many old examples.

* tidy-up - change all file endings and line breaks to unix.

* tidy-up - co-locate example user scripts and tasklists in the example folder. I think this makes more sense since these files are used together only.

* update readme to be somewhat more current.

### CODE REVIEW

**Comment by tiborauer** [comment]
I would rather transfer test/demo data to OSF, if @rhodricusack also agrees.

**Comment by tiborauer** [comment]
You can also find some BIDS data on [OSF](https://osf.io/9q7dv).

**Comment by tiborauer** [comment]
"Desired seed parameter (or type exit to abort):aap_parameters_defaults_RHUL.xml
created new parameter set in ...aa_parametersets/aap_parameters_user.xml
you may need to edit this file further to reflect local configuration"

I find it a bit worrying becuase any changes in aap_parameters_user will not be reflected in the original (site-specific) default, and vice versa. So one may need to edit both. 

I think the solution might be if aap_parameters_user.xml would only refer to the original one via xi:include.

**Comment by jooh** [comment]
Yes! I half-implemented a solution where aap_parameters_user.xml is generated as an empty XML file with only the include statement pointing at the specified parent. Then I ran out of time. I'm going to be on holiday for 2 weeks but I will sort this out when I'm back.

Regarding data sources and data retrieval, the most general solution would be datalad I think. We could think about coding up a little AA wrapper for it. Probably not for this PR though.

**Comment by tiborauer** [comment]
I am happy to carry on with the implementations and PR to your PR. I remember once we did that, but I am not sure about the actual commands. Could you refresh my memory?

I am not so sure about datalad. But we can investigate it.

**Comment by tiborauer** [comment]
OSF also uses googleapi, which is blocked at the CBSU; but should work other places. It certainly works at the RHUL.

I am finished with the tests at the RHUL, now running the CBSU ones. I have found a few issues and will submit a PR to your repo.

**Comment by tiborauer** [comment]
Why did you merged it if #163 also contained it?

**Comment by tiborauer** [comment]
I see now!:)

**Pull request merged**
