### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by jones-michael-s**
These are a few bug fixes and also some BIDS improvements. In no particular order:

1) tsdiffplot.m - fixed legend call for R2016b, use smaller font for title
2) aamod_tsdiffana.m - fixed renderer for R2016b, take down plot window on exit
3) aas_runFSCommand.m - remove obsolete lib options in call
4) meminfo.m - replaced my version that got deleted for some reason (thanks, Github). EDIT: Oops, my new meminfo is still sitting in my previous PR waiting for merge...
5) aamod_convert_epis.m - use FSL merge if available (because SPM merge isn't BIDS compat)
6) aa_export_toBIDS - document, also added option to copy required top level files if they exist
7) volumes2movie.m - various improvements: plot 6 not 3 images, average across slices
8) aamod_realign.m - restore incoming working directory on exit

### CODE REVIEW

**Comment by jones-michael-s** [comment]
Hello all,

We have been further testing my version of aamod_convert_epis in this PR (which uses FSL merge instead of SPM merge because SPM merge doesn't save TR which violates BIDS).

I noticed the new dicoms are 2x as large (because SPM saves as uint16 and FSL saves as int32). 

Is this a cause for concern? Suddenly doubling the file size might potentially create storage or even processing problems.

If that's reason to reject my PR, that's ok -- I just want to be sure I don't break stuff. The downside will be aa output will fail BIDS validation.

Regards
Mike

**Comment by jones-michael-s** [comment]
> Have you checked how the outputs of further stages (using SPM functions) look like? Do they still have correct TR? If not, is it an issue or do we make sure that we always use the output of conversion for export?

I have been using the new code locally (because we intend to eventually upload to openFMRI and want to be good BIDS citizens) and have seen no problems. Everything looks correct. However, I should document that everything is correct.

> I guess we could add another fslmaths command to convert the output to short. Would it change the result (of later stages)?

Taking a step back -- shouldn't it be possible to just write TR into the damn nifti header somehow? Even if its some C code or whatever. Sure seems like a cleaner fix. 

I just don't know enough about nifti headers to try it. Does anybody know any experts?

**Comment by tiborauer** [comment]
I have modified spm_file_merge to accept TR input and the corresponding aamodules to use this functionality: see [my commit](https://github.com/tiborauer/automaticanalysis/commit/3ae94cdd42d5140aed772cbaba0878527a47f349)

**Comment by jooh** [comment]
Please update to reflect the current AA master after Tibor's changes, and I will get the tests running.

**Comment by jones-michael-s** [comment]
I'm just going to close this and delete my fixes.

**Pull request closed without merging**
