### PR TITLE
Empty mask patch

### PR DESCRIPTION
**Pull request by dprice80**
In aamod_mask_fromsegment, when masking results in empty image, throw an error

### CODE REVIEW

**Comment by tiborauer** [comment]
@dprice80, @jooh can correct me, but I think you should perhaps merge the main branch so that your PR can be updated...

**Comment by dprice80** [comment]
Yes, you are right. I think I made a mistake there. I thought I had merged already.

**Comment by dprice80** [comment]
I'm a bit confused. When I compare with my main branch (which is up to date with Rhodri's) it seems the only difference is the change to the patch (the intended change). https://github.com/dprice80/automaticanalysis/compare/v5-devel...dprice80:dprice80-emptymask-patch?expand=1 

Same if I compare to Rhodri's main https://github.com/rhodricusack/automaticanalysis/compare/master...dprice80:dprice80-emptymask-patch?expand=1

**Comment by tiborauer** [comment]
Maybe @jooh can enlighten us. :)

**Comment by dprice80** [comment]
It's okay. I've just closed this one and reopened it using the up-to-date branch. There is probably a way to update the PR, but I don't have time to figure out right now.

**Pull request closed without merging**
